name: chw
description: CHW Management App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  datetime_picker_formfield: ^0.1.8
  location: ^2.3.5
  intl: any
  sqflite: ^0.13.0+1
  path_provider: ^0.4.1
  http: 0.12.0
  dio: 2.1.3
  rxdart: ^0.18.0
  shared_preferences: 0.4.3
  unique_identifier: ^0.0.3
  uuid: "^1.0.0"
  flutter_slidable: "^0.4.9"
  device_info: 0.4.0+1
  shimmer: 1.0.0
  firebase_core: ^0.4.0+9
  google_maps_flutter: ^0.5.21+7
  connectivity: ^0.4.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/furaha_yangu.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/bg.jpeg
   - assets/bg.jpg
   - assets/logo1.png
   - assets/meeting.jpg
   - assets/download.jpeg
   - assets/usaid.png
   - assets/group.png
   - assets/ipc.png
   - assets/mid-media.png
   - assets/user.png
   - assets/data_entry.png
   - assets/dashboard.png
   - assets/e-learning.png
   - assets/lock.png
   - assets/loader.gif
   - assets/banner.jpg
   - assets/village.png
   - assets/villageP.jpg
   - assets/sitetereki.jpg
   - assets/furaha_yangu.png
   - assets/sitetereki_logo.png
   - assets/naweza_logo.png
   - assets/logo_transparent_background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700
    - family: AvertaFont
      fonts:
        - asset: assets/fonts/averta-light-webfont.ttf
        - asset: assets/fonts/averta-regular-webfont.ttf
        - asset: assets/fonts/averta-semibold-webfont.ttf
    - family: Monospace
      fonts:
        - asset: assets/fonts/MonospaceTypewriter.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
